# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalan-r <fgalan-r@student.42malaga.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/25 20:07:21 by fgalan-r          #+#    #+#              #
#    Updated: 2022/04/25 20:07:24 by fgalan-r         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
SRC = ft_isalpha.c ft_toupper.c ft_isdigit.c ft_tolower.c ft_isalnum.c \
ft_isascii.c ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c \
ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_memchr.c \
ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c \
ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c \
ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_strncmp.c \
get_next_line.c

BONUS = ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c \
ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c

OBJS = $(SRC:.c=.o)
BONUSOBJS = $(BONUS:.c=.o)
CC	= gcc
CFLAGS = -Wall -Werror -Wextra
RM	= rm -f

$(NAME) :
	$(CC) -c $(CFLAGS) $(SRC)
	ar cr $(NAME) $(OBJS)

bonus :
	$(CC) -c $(CFLAGS) $(BONUS)
	ar cr $(NAME) $(BONUSOBJS)

all : $(NAME) bonus

clean :
	$(RM) $(OBJS) $(BONUSOBJS)
fclean : clean
	$(RM) $(NAME)
re : fclean all

.PHONY : all clean fclean re
